import React from 'react';
import Head from 'next/head';
import Nav from '../Nav/Nav';
import Footer from '../Footer/Footer';

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Smithsworkltd - Diligence / Excellence / Integrity</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.png' />
      </Head>
      <Nav />
      <main>{children}</main>
      <Footer />
    </>
  );
};

export default Layout;
